#!/usr/bin/env bash
# xteink fork: regenerate src/network/XteinkCaBundle.h from PEM root files.
#
# Usage: scripts/xteink-gen-ca-bundle.sh [CERT_DIR]
#   CERT_DIR defaults to /etc/ssl/certs (Debian/Ubuntu ca-certificates, which
#   ships Mozilla's root program). Rotation steps live in docs/xteink/tls.md.
#
# The root list below is the whole trust policy of the firmware: every HTTPS
# request made through HttpDownloader verifies against exactly these roots.
set -euo pipefail

CERT_DIR="${1:-/etc/ssl/certs}"
ROOT_DIR="$(cd "$(dirname "$0")/.." && pwd)"
OUT="$ROOT_DIR/src/network/XteinkCaBundle.h"

ROOTS=(
  ISRG_Root_X1
  ISRG_Root_X2
  GTS_Root_R1
  GTS_Root_R4
  Sectigo_Public_Server_Authentication_Root_E46
)

{
  echo '#pragma once'
  echo
  echo '// xteink fork: pinned root CAs for verified HTTPS. GENERATED by'
  echo '// scripts/xteink-gen-ca-bundle.sh -- do not edit by hand. Policy, sources,'
  echo '// expiry dates and the rotation procedure: docs/xteink/tls.md.'
  echo '//'
  for name in "${ROOTS[@]}"; do
    pem="$CERT_DIR/$name.pem"
    [ -f "$pem" ] || { echo "missing $pem" >&2; exit 1; }
    subj="$(openssl x509 -in "$pem" -noout -subject -nameopt RFC2253 | sed 's/^subject=//')"
    end="$(openssl x509 -in "$pem" -noout -enddate | sed 's/^notAfter=//')"
    fp="$(openssl x509 -in "$pem" -noout -fingerprint -sha256 | sed 's/^.*=//')"
    echo "//   $subj"
    echo "//     notAfter $end"
    echo "//     SHA-256 $fp"
  done
  echo
  echo '// Concatenated PEM, read by wolfSSL_CTX_load_verify_buffer (a PEM buffer'
  echo '// is processed as a chain of CA certificates). inline constexpr keeps one'
  echo '// copy in flash (.rodata); nothing is copied to DRAM until a handshake'
  echo '// parses it.'
  echo '// clang-format off'
  echo 'inline constexpr char XTEINK_CA_BUNDLE_PEM[] ='
  for name in "${ROOTS[@]}"; do
    pem="$CERT_DIR/$name.pem"
    echo "    // $name"
    openssl x509 -in "$pem" -outform PEM | sed 's/^/    "/; s/$/\\n"/'
  done
  echo '    ;'
  echo '// clang-format on'
  echo
  echo "inline constexpr int XTEINK_CA_BUNDLE_COUNT = ${#ROOTS[@]};"
} >"$OUT"

echo "wrote $OUT (${#ROOTS[@]} roots)"
